version: "3"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres:10.17
    container_name: database_postgres
    restart: unless-stopped
    ports: 
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=rentx"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - node-network

  # app:
  #   build: 
  #     context: .
  #   container_name: rentx
  #   restart: always
  #   tty: true
  #   ports: 
  #     - "3333:3333"
  #     - "9229:9229" #Você pode inserir essa porta tbm pra poder usar o debug
  #   volumes: 
  #     - .:/usr/app
  #   depends_on:
  #     - database
  #   networks:
  #     - node-network

networks:
  node-network :
    driver: bridge

volumes:
  pgdata:
    driver: local